- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container images list-tags gcr.io/$PROJECT_ID/hugo --format=json > gcrimagelist.json
    gcloud container images list-tags gcr.io/$PROJECT_ID/frbtools --format=json > gcrfrbimglist.json
  id: 'check-images'
